import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { ReactElement } from 'react'
import Layout from '../components/common/layout'
import PostItemCard from '../components/post/PostItemCard'
import { adiminDB } from '../firebase/server'
import { Post } from '../types/post'
import { NextPageWithLayout } from './_app' // Import Swiper React components
import { Swiper, SwiperSlide } from 'swiper/react'

// Import Swiper styles
import 'swiper/css'

const Home: NextPageWithLayout<
  InferGetStaticPropsType<typeof getStaticProps>
> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mt-6">
        <div className="mb-4">
          <Swiper loop spaceBetween={50} slidesPerView={1}>
            {new Array(5).fill(null).map((_, index) => {
              return (
                <SwiperSlide key={index}>
                  <div className="bg-gray-100 aspect-video flex justify-center items-center">
                    <p>{index}</p>
                  </div>
                </SwiperSlide>
              )
            })}
          </Swiper>
        </div>

        <h2 className="mb-4">記事の一覧</h2>
        {posts?.length ? (
          <ul className="space-y-4">
            {posts.map((post, index) => {
              return <PostItemCard key={index} post={post} />
            })}
          </ul>
        ) : (
          <p>記事がありません</p>
        )}
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async () => {
  const response = await adiminDB
    .collection('posts')
    .orderBy('createdAt', 'desc')
    .limit(20)
    .get()
  const posts = response.docs.map((doc) => doc.data() as Post)
  if (!posts) {
    return {
      notFound: true
    }
  }
  return {
    props: { posts }
  }
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default Home
