import Head from 'next/head'
import { ReactElement } from 'react'
import Layout from '../components/common/layout'
import { useAuth } from '../context/auth'
import { NextPageWithLayout } from './_app'

const Home: NextPageWithLayout = () => {
  const { user } = useAuth()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mt-6">
        <p>{user?.name}</p>
        <p>{user?.nickname}</p>
        <p>{user?.profile}</p>
      </main>
    </div>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default Home
